/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/Tree.glb -o components/Tree.jsx -r public -k
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Tree(props) {
  const { nodes, materials } = useGLTF("/models/Tree.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Tree_4" rotation={[-Math.PI / 2, 0, 0]} scale={31.046}>
        <mesh
          name="Tree_4_1"
          geometry={nodes.Tree_4_1.geometry}
          material={materials.Tree_Wood}
        />
        <mesh
          name="Tree_4_2"
          geometry={nodes.Tree_4_2.geometry}
          material={materials.Tree_Green}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Tree.glb");
